### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by ligi** [jubmoji/jubmoji.quest#168]
![image](https://github.com/jubmoji/jubmoji.quest/assets/111600/bf235c6b-1f9f-4383-839d-facd87548e45)

![image](https://github.com/jubmoji/jubmoji.quest/assets/111600/9cac9605-d662-4f80-ae11-8dedbe842529)

```
framework-80ea8c0f440c6a32.js:9 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at mh (framework-80ea8c0f440c6a32.js:9:92730)
    at ri (framework-80ea8c0f440c6a32.js:9:66302)
    at ref (jubmojis-e7a8602c6365ad8e.js:1:12841)
    at Sj (framework-80ea8c0f440c6a32.js:9:84295)
    at lk (framework-80ea8c0f440c6a32.js:9:91458)
    at jk (framework-80ea8c0f440c6a32.js:9:111105)
    at framework-80ea8c0f440c6a32.js:9:111116
    at Qk (framework-80ea8c0f440c6a32.js:9:111628)
    at Fk (framework-80ea8c0f440c6a32.js:9:96297)
    at jg (framework-80ea8c0f440c6a32.js:9:44900)
Mi @ framework-80ea8c0f440c6a32.js:9
main-f34b077c56f27e4b.js:1 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at mh (framework-80ea8c0f440c6a32.js:9:92730)
    at ri (framework-80ea8c0f440c6a32.js:9:66302)
    at ref (jubmojis-e7a8602c6365ad8e.js:1:12841)
    at Sj (framework-80ea8c0f440c6a32.js:9:84295)
    at lk (framework-80ea8c0f440c6a32.js:9:91458)
    at jk (framework-80ea8c0f440c6a32.js:9:111105)
    at framework-80ea8c0f440c6a32.js:9:111116
    at Qk (framework-80ea8c0f440c6a32.js:9:111628)
    at Fk (framework-80ea8c0f440c6a32.js:9:96297)
    at jg (framework-80ea8c0f440c6a32.js:9:44900)
```
![image](https://github.com/jubmoji/jubmoji.quest/assets/111600/5a90126b-91e8-4e79-b378-1083cbcd3430)

**Comment by vb7401** [comment]
Thank you @ligi for finding! Looks like it's a result of https://legacy.reactjs.org/docs/error-decoder.html/?invariant=185
